### ISSUE TITLE
Vimeo Upload Error - VimeoRequestException: Connection timed out

### ISSUE THREAD

**Issue by Mr-Anonymous** [vimeo/laravel#63]
The vimeo uploads has been working for over a year so far without a problem and there has been no changes to the server php or sql or any other settings. However, the past 3 days, some of the slighly large video uploads are failing and I get the following error in the laravel log:

```
[2019-10-14 04:22:38] production.ERROR: Vimeo\Exceptions\VimeoRequestException: Unable to complete request.[Connection timed out after 30001 milliseconds] in /home/myapp/vendor/vimeo/vimeo-api/src/Vimeo/Vimeo.php:449
Stack trace:
#0 /home/myapp/vendor/vimeo/vimeo-api/src/Vimeo/Vimeo.php(529): Vimeo\Vimeo->_request('https://1512435...', Array)
#1 /home/myapp/vendor/vimeo/vimeo-api/src/Vimeo/Vimeo.php(282): Vimeo\Vimeo->perform_upload('/home/myapp...', Array)
#2 /home/myapp/vendor/graham-campbell/manager/src/AbstractManager.php(236): Vimeo\Vimeo->upload('/home/myapp...')
#3 /home/myapp/bootstrap/cache/compiled.php(6468): GrahamCampbell\Manager\AbstractManager->__call('upload', Array)
#4 /home/myapp/app/Jobs/VimeoUploadJob.php(58): Illuminate\Support\Facades\Facade::__callStatic('upload', Array)
#5 [internal function]: App\Jobs\VimeoUploadJob->handle()
#6 /home/myapp/bootstrap/cache/compiled.php(1375): call_user_func_array(Array, Array)
#7 /home/myapp/bootstrap/cache/compiled.php(9961): Illuminate\Container\Container->call(Array)
#8 /home/myapp/bootstrap/cache/compiled.php(10076): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(App\Jobs\VimeoUploadJob))
#9 /home/myapp/bootstrap/cache/compiled.php(10054): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Jobs\VimeoUploadJob))
#10 /home/myapp/bootstrap/cache/compiled.php(9964): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#11 /home/myapp/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(47): Illuminate\Bus\Dispatcher->dispatchNow(Object(App\Jobs\VimeoUploadJob), false)
#12 /home/myapp/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(73): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\BeanstalkdJob), Array)
#13 /home/myapp/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(203): Illuminate\Queue\Jobs\Job->fire()
#14 /home/myapp/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(153): Illuminate\Queue\Worker->process('beanstalkd', Object(Illuminate\Queue\Jobs\BeanstalkdJob), Object(Illuminate\Queue\WorkerOptions))
#15 /home/myapp/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(75): Illuminate\Queue\Worker->runNextJob('beanstalkd', 'high,default,pd...', Object(Illuminate\Queue\WorkerOptions))
#16 /home/myapp/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(100): Illuminate\Queue\Worker->daemon('beanstalkd', 'high,default,pd...', Object(Illuminate\Queue\WorkerOptions))
#17 /home/myapp/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(84): Illuminate\Queue\Console\WorkCommand->runWorker('beanstalkd', 'high,default,pd...')
#18 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()
#19 /home/myapp/bootstrap/cache/compiled.php(1375): call_user_func_array(Array, Array)
#20 /home/myapp/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#21 /home/myapp/vendor/symfony/console/Command/Command.php(261): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /home/myapp/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /home/myapp/vendor/symfony/console/Application.php(817): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /home/myapp/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /home/myapp/vendor/symfony/console/Application.php(116): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /home/myapp/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /home/myapp/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 {main}  
```

What may be the reason here please? 

I use Laravel 5.3, php 7 and use beanstalkd to process queue workers that does the uploading from my server to vimeo via API.

**Comment by Mr-Anonymous** [comment]
Sorry, does anyone have any suggestions on what might be the issue here please? I am receiving numerous logs with the `Connection timed out after 30001 milliseconds` error message everyday and have no idea what is causing this. It doesn't happen to all videos and it happens to some videos that are longer the 25 seconds in duration it seems. Is this issue from the Vimeo server side or is there something in my server that needs to be reviewed? Any help will be appreciated.

**Comment by mlenton** [comment]
Hello, we are seeing same here, though with `vimeo/vimeo-api` version 2.0.5 for PHP.

Did you find the root cause here @Mr-Anonymous ?
